name: 🐛 Bug Report
description: File a bug report to help us improve BCCE
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏
        
        Before submitting, please:
        - Search existing issues to avoid duplicates
        - Run `bcce doctor` to check your environment
        - Include all relevant information below

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have run `bcce doctor` to check my environment
          required: true
        - label: I am using the latest version of BCCE
          required: true

  - type: input
    id: version
    attributes:
      label: BCCE Version
      description: What version of BCCE are you using?
      placeholder: "e.g., v1.2.3 (from bcce --version)"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu)
        - Linux (CentOS/RHEL)
        - Linux (Other)
        - Docker
    validations:
      required: true

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      description: How did you install BCCE?
      options:
        - NPM
        - Direct binary download
        - Docker
        - Homebrew
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "Describe what happened and what you expected to happen"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. See error '...'
        3. Expected '...' but got '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: |
        Paste any relevant error messages or logs here.
        Run with `--verbose` flag for detailed output.
      render: shell
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: |
        Paste relevant configuration files (remove sensitive data)
      render: yaml
    validations:
      required: false

  - type: textarea
    id: doctor
    attributes:
      label: Environment Info
      description: |
        Run `bcce doctor` and paste the output here (remove sensitive data)
      render: shell
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low (Minor inconvenience)
        - Medium (Impacts workflow)
        - High (Blocks functionality)
        - Critical (System unusable)
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here:
        - Screenshots
        - Related issues
        - Workarounds you've tried
        - Impact on your workflow
    validations:
      required: false